// client/src/app/features/tasks/task-form/task-form.component.ts
import { Component, inject, input, signal, computed, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import {
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonContent,
  IonInput,
  IonTextarea,
  IonSelect,
  IonSelectOption,
  IonItem,
  IonLabel,
  ModalController,
  AlertController,
} from '@ionic/angular/standalone';

import { TasksService, Task, TaskStatus } from '../tasks.service';

@Component({
  selector: 'app-task-form',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonButtons,
    IonButton,
    IonContent,
    IonInput,
    IonTextarea,
    IonSelect,
    IonSelectOption,
    IonItem,
    IonLabel,
  ],
  template: `
    <ion-header>
      <ion-toolbar>
        <ion-title>{{ isEdit() ? 'Edit task' : 'New task' }}</ion-title>
        <ion-buttons slot="end">
          <ion-button type="button" fill="clear" (click)="close()">Cancel</ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
    <ion-content class="task-form-content">
      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="task-form">
        @if (errorMessage()) {
          <p class="error">{{ errorMessage() }}</p>
        }
        <div class="field-group">
          <ion-item lines="none" class="task-form-item">
            <ion-label position="stacked">Title</ion-label>
            <ion-input
              formControlName="title"
              placeholder="Task title"
              type="text"
            />
          </ion-item>
          @if (form.get('title')?.invalid && form.get('title')?.touched) {
            <p class="field-error">Title is required</p>
          }
        </div>
        <div class="field-group">
          <ion-item lines="none" class="task-form-item">
            <ion-label position="stacked">Description <span class="optional">(optional)</span></ion-label>
            <ion-textarea
              formControlName="description"
              placeholder="Task description"
              rows="3"
            />
          </ion-item>
        </div>
        <div class="field-group">
          <ion-item lines="none" class="task-form-item">
            <ion-label position="stacked">Due date <span class="optional">(optional)</span></ion-label>
            <ion-input
              formControlName="dueAt"
              type="datetime-local"
            />
          </ion-item>
        </div>
        @if (isEdit()) {
          <div class="field-group">
            <ion-item lines="none" class="task-form-item">
              <ion-label position="stacked">Status</ion-label>
              <ion-select formControlName="status" placeholder="Status" interface="alert">
                <ion-select-option value="PENDING">Pending</ion-select-option>
                <ion-select-option value="DONE">Done</ion-select-option>
                <ion-select-option value="CANCELED">Canceled</ion-select-option>
              </ion-select>
            </ion-item>
          </div>
        }
        <ion-button
          type="submit"
          expand="block"
          color="primary"
          class="submit-btn"
          [disabled]="form.invalid || saving()"
        >
          {{ saving() ? 'Saving…' : (isEdit() ? 'Save' : 'Create') }}
        </ion-button>
      </form>
    </ion-content>
  `,
  styles: `
    .task-form-content {
      --background: var(--tf-card);
    }
    .task-form {
      padding: 1.25rem 1rem 1.5rem;
      max-width: 28rem;
      margin: 0 auto;
    }
    .task-form .error {
      color: var(--ion-color-danger);
      margin: 0 0 1.25rem 0;
      padding: 0.75rem 1rem;
      background: color-mix(in srgb, var(--ion-color-danger) 12%, transparent);
      border-radius: 8px;
      font-size: 0.875rem;
    }
    .field-group {
      margin-bottom: 1.25rem;
    }
    .field-error {
      color: var(--ion-color-danger);
      font-size: 0.8125rem;
      margin: 0.375rem 0 0;
      padding-left: 0.25rem;
    }
    .task-form-item {
      --background: var(--tf-input-bg);
      --padding-start: 0.75rem;
      --padding-end: 0.75rem;
      --inner-padding-end: 0;
      --min-height: 3rem;
      --border-radius: 8px;
      border: 1px solid var(--tf-border);
      border-radius: 8px;
      margin-bottom: 0;
    }
    .task-form-item:focus-within {
      border-color: var(--tf-primary);
      box-shadow: 0 0 0 2px color-mix(in srgb, var(--tf-primary) 20%, transparent);
    }
    .task-form-item ion-label {
      color: var(--tf-label);
      font-weight: 500;
      margin-bottom: 0.25rem;
    }
    .optional {
      color: var(--tf-text-muted);
      font-weight: 400;
    }
    .submit-btn {
      margin-top: 0.5rem;
      font-weight: 600;
      letter-spacing: 0.02em;
      --padding-top: 0.75rem;
      --padding-bottom: 0.75rem;
    }
  `,
})
export class TaskFormComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly tasksService = inject(TasksService);
  private readonly modalController = inject(ModalController);
  private readonly alertController = inject(AlertController);

  task = input<Task | null>(null);

  readonly form = this.fb.nonNullable.group({
    title: ['', Validators.required],
    description: [''],
    dueAt: [''],
    status: ['PENDING' as TaskStatus],
  });

  readonly saving = signal(false);
  readonly errorMessage = signal<string | null>(null);

  readonly isEdit = computed(() => this.task() != null);

  ngOnInit(): void {
    const t = this.task();
    if (t) {
      const dueAt = t.dueAt
        ? new Date(t.dueAt).toISOString().slice(0, 16)
        : '';
      this.form.reset({
        title: t.title,
        description: t.description ?? '',
        dueAt,
        status: t.status,
      });
    }
  }

  close(): void {
    this.modalController.dismiss(null, 'cancel');
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid || this.saving()) return;

    if (this.isEdit()) {
      const alert = await this.alertController.create({
        header: 'Save changes?',
        message: 'Save changes to this task?',
        buttons: [
          { text: 'Cancel', role: 'cancel' },
          { text: 'Save', role: 'confirm' },
        ],
      });
      await alert.present();
      const { role } = await alert.onDidDismiss();
      if (role !== 'confirm') return;
    }

    this.errorMessage.set(null);
    this.saving.set(true);

    const { title, description, dueAt, status } = this.form.getRawValue();
    const dueAtOrUndefined = dueAt.trim()
      ? new Date(dueAt).toISOString()
      : undefined;
    const descOrUndefined = description.trim() || undefined;

    const taskId = this.task()?.id;
    if (taskId) {
      this.tasksService
        .updateTask(taskId, {
          title,
          description: descOrUndefined ?? null,
          dueAt: dueAtOrUndefined ?? null,
          status,
        })
        .subscribe({
          next: (saved) => {
            this.saving.set(false);
            this.modalController.dismiss(saved, 'saved');
          },
          error: (err: Error) => {
            this.errorMessage.set(err.message);
            this.saving.set(false);
          },
        });
    } else {
      this.tasksService
        .createTask({
          title,
          description: descOrUndefined,
          dueAt: dueAtOrUndefined,
        })
        .subscribe({
          next: (saved) => {
            this.saving.set(false);
            this.modalController.dismiss(saved, 'saved');
          },
          error: (err: Error) => {
            this.errorMessage.set(err.message);
            this.saving.set(false);
          },
        });
    }
  }
}

// client/src/features/tasks/TaskForm.tsx
import { useCallback, useEffect, useState, type FormEvent, type ReactElement } from 'react';

import { Button, ConfirmDialog, Input, Select, Textarea } from '../../components/ui';
import type { SelectOption } from '../../components/ui/Select';
import { createTask, updateTask } from '../../lib/tasksApi';
import type { Task, TaskStatus } from '../../lib/types';
import './TaskForm.css';

const STATUS_OPTIONS: SelectOption[] = [
  { value: 'PENDING', label: 'Pending' },
  { value: 'DONE', label: 'Done' },
  { value: 'CANCELED', label: 'Canceled' },
];

export type TaskFormProps = {
  task: Task | null;
  onClose: () => void;
  onSaved: () => void;
};

function pad2(value: number): string {
  return String(value).padStart(2, '0');
}

function dueAtToLocalInput(iso: string | null): string {
  if (iso === null) {
    return '';
  }
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) {
    return '';
  }
  return `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}T${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
}

export function localInputToIso(local: string): string | undefined {
  const trimmed = local.trim();
  if (trimmed.length === 0) {
    return undefined;
  }
  const parsed = new Date(trimmed);
  if (Number.isNaN(parsed.getTime())) {
    throw new Error('Invalid due date');
  }
  return parsed.toISOString();
}

export function TaskForm(props: TaskFormProps): ReactElement {
  const isEdit = props.task !== null;

  const [title, setTitle] = useState<string>('');
  const [description, setDescription] = useState<string>('');
  const [dueAt, setDueAt] = useState<string>('');
  const [status, setStatus] = useState<TaskStatus>('PENDING');
  const [titleTouched, setTitleTouched] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [confirmOpen, setConfirmOpen] = useState<boolean>(false);

  useEffect(() => {
    const task = props.task;
    if (task !== null) {
      setTitle(task.title);
      setDescription(task.description ?? '');
      setDueAt(dueAtToLocalInput(task.dueAt));
      setStatus(task.status);
    } else {
      setTitle('');
      setDescription('');
      setDueAt('');
      setStatus('PENDING');
    }
    setTitleTouched(false);
    setErrorMessage(null);
    setSaving(false);
    setConfirmOpen(false);
  }, [props.task]);

  const titleInvalid = title.trim().length === 0;

  const close = useCallback((): void => {
    props.onClose();
  }, [props]);

  const submit = useCallback((): void => {
    if (titleInvalid || saving) {
      return;
    }

    setErrorMessage(null);
    setSaving(true);

    let dueAtIso: string | undefined;
    try {
      dueAtIso = localInputToIso(dueAt);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Invalid due date';
      setErrorMessage(message);
      setSaving(false);
      return;
    }

    const descOrUndefined = description.trim().length > 0 ? description.trim() : undefined;
    const taskId = props.task?.id;

    if (taskId !== undefined) {
      updateTask(taskId, {
        title,
        description: descOrUndefined ?? null,
        dueAt: dueAtIso ?? null,
        status,
      })
        .then(() => {
          setSaving(false);
          props.onSaved();
        })
        .catch((err: Error) => {
          setErrorMessage(err.message);
          setSaving(false);
        });
    } else {
      createTask({
        title,
        description: descOrUndefined,
        dueAt: dueAtIso,
      })
        .then(() => {
          setSaving(false);
          props.onSaved();
        })
        .catch((err: Error) => {
          setErrorMessage(err.message);
          setSaving(false);
        });
    }
  }, [title, description, dueAt, status, titleInvalid, saving, props]);

  const onSubmit = useCallback(
    (event: FormEvent<HTMLFormElement>): void => {
      event.preventDefault();
      if (titleInvalid || saving) {
        return;
      }
      if (isEdit) {
        setConfirmOpen(true);
        return;
      }
      submit();
    },
    [titleInvalid, saving, isEdit, submit],
  );

  const onConfirmDismiss = useCallback(
    (role: 'cancel' | 'destructive' | 'confirm' | 'backdrop'): void => {
      setConfirmOpen(false);
      if (role === 'confirm') {
        submit();
      }
    },
    [submit],
  );

  return (
    <>
      <header className="task-form-header">
        <h2 className="task-form-title">{isEdit ? 'Edit task' : 'New task'}</h2>
        <Button
          type="button"
          fill="clear"
          size="default"
          expand={undefined}
          color="default"
          disabled={false}
          className={undefined}
          aria-label={undefined}
          onClick={close}
        >
          Cancel
        </Button>
      </header>
      <form className="task-form" onSubmit={onSubmit}>
        {errorMessage !== null ? <p className="task-form__error">{errorMessage}</p> : null}
        <div className="field-group">
          <label className="field-label" htmlFor="task-title">
            Title
          </label>
          <Input
            id="task-title"
            type="text"
            value={title}
            placeholder="Task title"
            disabled={false}
            autoComplete={undefined}
            className="task-form-input"
            onChange={setTitle}
            onBlur={() => setTitleTouched(true)}
          />
          {titleTouched && titleInvalid ? (
            <p className="field-error">Title is required</p>
          ) : null}
        </div>
        <div className="field-group">
          <label className="field-label" htmlFor="task-description">
            Description <span className="optional">(optional)</span>
          </label>
          <Textarea
            id="task-description"
            value={description}
            placeholder="Task description"
            rows={3}
            disabled={false}
            className="task-form-input"
            onChange={setDescription}
          />
        </div>
        <div className="field-group">
          <label className="field-label" htmlFor="task-due-at">
            Due date <span className="optional">(optional)</span>
          </label>
          <Input
            id="task-due-at"
            type="datetime-local"
            value={dueAt}
            placeholder={undefined}
            disabled={false}
            autoComplete={undefined}
            className="task-form-input"
            onChange={setDueAt}
            onBlur={undefined}
          />
        </div>
        {isEdit ? (
          <div className="field-group">
            <label className="field-label" htmlFor="task-status">
              Status
            </label>
            <Select
              value={status}
              options={STATUS_OPTIONS}
              placeholder={undefined}
              disabled={false}
              className="task-form-select"
              onChange={(value) => setStatus(value as TaskStatus)}
            />
          </div>
        ) : null}
        <Button
          type="submit"
          fill="solid"
          size="default"
          expand="block"
          color="default"
          disabled={titleInvalid || saving}
          className="submit-btn"
          aria-label={undefined}
          onClick={undefined}
        >
          {saving ? 'Saving…' : isEdit ? 'Save' : 'Create'}
        </Button>
      </form>
      <ConfirmDialog
        isOpen={confirmOpen}
        header="Save changes?"
        message="Save changes to this task?"
        buttons={[
          { text: 'Cancel', role: 'cancel' },
          { text: 'Save', role: 'confirm' },
        ]}
        onDismiss={onConfirmDismiss}
      />
    </>
  );
}
